In [6]:
import numpy as np

In [7]:
# what is numpy 
# numpy array and python array

In [8]:
# creating numpy array

a=np.array([1,2,3])
print(type(a))
a

<class 'numpy.ndarray'>


array([1, 2, 3])

In [9]:
b=np.array([[1,2,3],[4,5,7]])
b

array([[1, 2, 3],
       [4, 5, 7]])

In [10]:
b.dtype

dtype('int64')

In [11]:
b.shape

(2, 3)

In [12]:
b.size

6

In [13]:
c=np.array(['prashant','hello']).astype('str')
c

array(['prashant', 'hello'], dtype='<U8')

In [14]:
np.arange(0,12).reshape(3,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [15]:
np.ones((2,3)).astype('int')

array([[1, 1, 1],
       [1, 1, 1]])

In [16]:
np.zeros((2,3),'int')

array([[0, 0, 0],
       [0, 0, 0]])

In [18]:
np.round(np.random.random((3,4)),3)

array([[0.508, 0.011, 0.93 , 0.243],
       [0.262, 0.969, 0.096, 0.23 ],
       [0.957, 0.74 , 0.556, 0.387]])

In [19]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [20]:
np.identity(4).astype('int')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [21]:
np.random.randint(1,10,(1,5))

array([[8, 1, 4, 9, 5]], dtype=int32)

In [22]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
# fill with garbage value which is present in ram
np.empty((2,2))

array([[2.41907520e-312, 2.44029516e-312],
       [2.05833592e-312, 2.46151512e-312]])

In [24]:
np.full((2,2),12)

array([[12, 12],
       [12, 12]])

In [25]:
np.arange(14).reshape(2,7).ndim

2

In [26]:
np.arange(14).reshape(1,14).size

14

In [27]:
np.arange(14).reshape(1,14).itemsize

8

In [28]:
c.itemsize

32

In [29]:
a.dtype,b.dtype,c.dtype

(dtype('int64'), dtype('int64'), dtype('<U8'))

In [30]:
a1=np.arange(10,16).reshape(2,3)
a2=np.arange(0,6).reshape(2,3)
a1,a2

(array([[10, 11, 12],
        [13, 14, 15]]),
 array([[0, 1, 2],
        [3, 4, 5]]))

In [31]:
a1+a2

array([[10, 12, 14],
       [16, 18, 20]])

In [32]:
a1**a2

array([[     1,     11,    144],
       [  2197,  38416, 759375]])

In [33]:
a2[a1>5]

array([0, 1, 2, 3, 4, 5])

In [34]:
a1 == a2

array([[False, False, False],
       [False, False, False]])

In [35]:
a1>a2+9

array([[ True,  True,  True],
       [ True,  True,  True]])

In [36]:
a1/a2

C:\Users\PRASHANT\AppData\Local\Temp\ipykernel_1604\3705041958.py:1: RuntimeWarning: divide by zero encountered in divide
  a1/a2


array([[        inf, 11.        ,  6.        ],
       [ 4.33333333,  3.5       ,  3.        ]])

In [37]:
a1.max()

np.int64(15)

In [39]:
a2.min(axis=1),a2.mean(),a2.sum(),np.var(a2)

(array([0, 3]), np.float64(2.5), np.int64(15), np.float64(2.9166666666666665))

In [40]:
a2

array([[0, 1, 2],
       [3, 4, 5]])

In [41]:
np.mean(a2,axis=1,dtype='int64')

array([1, 4])

In [42]:
np.sign(a2)

array([[0, 1, 1],
       [1, 1, 1]])

In [43]:
# numpy has lots of function read documentation for more information

In [44]:
a1 = np.arange(1,13).reshape(3,4)
a2=np.arange(13,1,-1).reshape(4,3)

print("a1: \n",a1)
print("a2: \n",a2)
np.dot(a1,a2)

a1: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
a2: 
 [[13 12 11]
 [10  9  8]
 [ 7  6  5]
 [ 4  3  2]]


array([[ 70,  60,  50],
       [206, 180, 154],
       [342, 300, 258]])

In [115]:
np.round(np.log(a1),2)

array([[0.  , 0.69, 1.1 , 1.39],
       [1.61, 1.79, 1.95, 2.08],
       [2.2 , 2.3 , 2.4 , 2.48]])

In [46]:
np.round(np.exp(a1),2)

array([[2.7200000e+00, 7.3900000e+00, 2.0090000e+01, 5.4600000e+01],
       [1.4841000e+02, 4.0343000e+02, 1.0966300e+03, 2.9809600e+03],
       [8.1030800e+03, 2.2026470e+04, 5.9874140e+04, 1.6275479e+05]])

In [47]:
temp=np.linspace(-10,10,10).reshape(5,2)
temp

array([[-10.        ,  -7.77777778],
       [ -5.55555556,  -3.33333333],
       [ -1.11111111,   1.11111111],
       [  3.33333333,   5.55555556],
       [  7.77777778,  10.        ]])

In [48]:
np.floor(temp)

array([[-10.,  -8.],
       [ -6.,  -4.],
       [ -2.,   1.],
       [  3.,   5.],
       [  7.,  10.]])

In [49]:
np.ceil(temp)

array([[-10.,  -7.],
       [ -5.,  -3.],
       [ -1.,   2.],
       [  4.,   6.],
       [  8.,  10.]])

In [50]:
# indexing 

a1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
a1[0]

array([1, 2, 3, 4])

In [52]:
a1[1,1]

np.int64(6)

In [53]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
a[2:5]

array([3, 4, 5])

In [55]:
a1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [56]:
a1[0:2,:1]

array([[1],
       [5]])

In [57]:
a1[1:,[1,2]]

array([[ 6,  7],
       [10, 11]])

In [58]:
a1[::2,::3]

array([[ 1,  4],
       [ 9, 12]])

In [59]:
a1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [60]:
a1[::2,1::2]

array([[ 2,  4],
       [10, 12]])

In [61]:
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [62]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [63]:
for i in a1:
    print(i)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]


In [64]:
a1.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [65]:
np.transpose(a1)

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [66]:
np.ravel(a3)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [67]:
# staking 

a3=np.arange(12).reshape(3,4)
a4=np.arange(12,24).reshape(3,4)
a5=np.hstack((a3,a4))
a5

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [68]:
a6=np.vstack((a3,a4))
a6

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [69]:
# splitting

np.hsplit(a5,2)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [70]:
np.vsplit(a6,3)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [71]:
np.concatenate((a3,a4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [72]:
a=np.linalg.inv(np.random.randint(1,100,(3,3)))
a

array([[-0.00898389, -0.00014561,  0.0161841 ],
       [ 0.00166233,  0.01299291, -0.01082823],
       [ 0.01416261, -0.0046327 , -0.00174242]])

In [73]:
a @ np.linalg.inv(a)

array([[ 1.00000000e+00, -3.86671438e-17, -6.74291740e-17],
       [ 6.19380742e-17,  1.00000000e+00,  9.20397495e-17],
       [ 2.58282447e-19, -7.39218672e-17,  1.00000000e+00]])

In [74]:
np.cross(np.array([1,2,3]),np.array([2,3,4]))

array([-1,  2, -1])

In [75]:
x=np.random.randint(1,100,(1,10))
y=np.random.randint(1,100,(1,10))
np.cov(x*10,y)

array([[72445.55555556,    84.33333333],
       [   84.33333333,   681.56666667]])

In [76]:
np.cov(x*10,y*10)

array([[72445.55555556,   843.33333333],
       [  843.33333333, 68156.66666667]])