In [1]:
import random
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,SGDRegressor
from sklearn.metrics import r2_score

In [2]:
data=pd.read_csv(r"E:\Datasets\Indian_housing_Delhi_data.csv",usecols=['house_size','latitude','longitude','price','numBathrooms'])
data.head()

,house_size,latitude,longitude,price,numBathrooms
0,400 sq ft,28.545561,77.254349,22000,1.0
1,400 sq ft,28.643259,77.132828,20000,1.0
2,500 sq ft,28.618677,77.053352,8500,1.0
3,"1,020 sq ft",28.712898,77.180000,48000,3.0
4,810 sq ft,28.723539,77.131424,20000,2.0


In [3]:
data['house_size']=data['house_size'].str.replace(",","")
def Number(data):
    for i in data.split():
        if i.isdigit():
            return i
        else:
            return data
data['house_size']=data['house_size'].apply(Number).astype('int')

In [4]:
data['numBathrooms'].fillna(0,inplace=True)

In [5]:
data.isna().sum()

house_size      0
latitude        0
longitude       0
price           0
numBathrooms    0
dtype: int64

In [6]:
X_train,X_test,y_train,y_test=train_test_split(data.drop(columns=['price']),data['price'],test_size=0.33,random_state=42)
scale=StandardScaler()
X_train=scale.fit_transform(X_train)
X_test=scale.transform(X_test)

In [7]:
lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred=lr.predict(X_test)
score=r2_score(y_test,y_pred)
score

0.5361597337432656

In [8]:
lr.coef_,lr.intercept_

(array([215742.66496505,   6815.63376764,   1485.57431585, -12019.50093974]),
 np.float64(224317.44985074608))

In [20]:
import random

In [67]:
y_train = np.array(y_train)
n=0.1
epoch=200
intercept=0
batch_size=1000
coef=np.ones(X_train.shape[1])
for i in range(epoch):

    for j in range(X_train.shape[0]//batch_size):
        idx=random.sample(range(0,X_train.shape[0]),batch_size)
        
        y_hat=intercept+ np.dot(X_train[idx],coef)
        intercept_der = -2 * np.mean(y_train[idx] - y_hat)
        intercept=intercept-(n* intercept_der)

        coef_der = (-2 * np.dot((y_train[idx]-y_hat), X_train[idx]))/batch_size
        coef=coef-(n*coef_der)

In [68]:
coef,intercept

(array([213672.90768447,   6211.84239791,    780.46523501, -15209.71950975]),
 np.float64(222796.63238274227))

In [69]:
lr.coef_,lr.intercept_

(array([215742.66496505,   6815.63376764,   1485.57431585, -12019.50093974]),
 np.float64(224317.44985074608))

In [70]:
y_pred = intercept + np.dot(X_test,coef)

In [71]:
score=r2_score(y_test,y_pred)
score

0.5373998024063067